name: do_test_app
services:
  - name: web
    environment_slug: python
    github:
      repo: Lumiwealth-Strategies/do_test
      branch: main
    build_command: pip install -r requirements.txt
    run_command: gunicorn app:app
    resources:
      instance_size_slug: basic-1vcpu-1gb
    envs:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        scope: run
        secret: secret_key
secrets:
  - name: secret_key
    value: your-super-secret-key