name: do_test_app
services:
  - name: web
    environment_slug: python
    github:
      repo: Lumiwealth-Strategies/do_test
      branch: main
    build_command: pip install -r requirements.txt
    run_command: gunicorn app:app
    resources:
      cpu: 1       # You can specify 1x or 2x CPU, depending on what you need
      memory: 512mb # Adjust memory to fit your needs
    envs:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your-super-secret-key